[[groups]]
  name = "trunkr"
  display_name = "trunkr"
  changelog_cmd = ["bumper", "builtins", "amendlog:default"]
  cat_cmd = ["bumper", "builtins", "cat:default"]
  current_cmd = ["bumper", "builtins", "current:default"]
  next_cmd = ["bumper", "builtins", "next:default"]
